#! /bin/bash

printf "\nWelcome to your writefreely instance!\n"

printf "\nTo view the applications logs type: journalctl -f -u writefreely\n"

printf "\nYour database root password is in /var/www/writefreely/.root.db.pass\n"
printf "Your application database account is:\n"
printf "  Username: writefreely\n"
printf "  Password: /var/www/writefreely/.user.db.pass\n"

printf "\nFor more information on administering a writefreely instance see:\n"
printf "  - https://writefreely.org/docs/latest/admin\n"
printf "  - https://github.com/writeas/writefreely\n"

printf "This installation includes basic fail2ban setup. The service will\n"
printf "be enabled by default after initial setup. To configure it further see:\n"
printf "  - https://www.fail2ban.org/\n"

printf "\nIf you need help: https://discuss.write.as is a great place to ask.\n\n"
